version: '3.9'
services:
  app:
    build: .
    command: node dist/server.cjs
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - APP_URL=http://localhost:3000
      - SQL_HOST=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_DB_NAME=spr
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    command: node dist/worker.cjs
    environment:
      - NODE_ENV=production
      - SQL_HOST=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_DB_NAME=spr
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spr
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  postgres_data:
